package com.websharp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.websharp.dao.EntityWorkLogDg;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_WORK_LOG_DG.
*/
public class EntityWorkLogDgDao extends AbstractDao<EntityWorkLogDg, Void> {

    public static final String TABLENAME = "ENTITY_WORK_LOG_DG";

    /**
     * Properties of entity EntityWorkLogDg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property OccurTime = new Property(0, String.class, "OccurTime", false, "OCCUR_TIME");
        public final static Property UserID = new Property(1, String.class, "UserID", false, "USER_ID");
        public final static Property UserName = new Property(2, String.class, "UserName", false, "USER_NAME");
        public final static Property OrgCode = new Property(3, String.class, "OrgCode", false, "ORG_CODE");
        public final static Property ParamType = new Property(4, String.class, "ParamType", false, "PARAM_TYPE");
        public final static Property ParamValue = new Property(5, String.class, "ParamValue", false, "PARAM_VALUE");
        public final static Property OfferID = new Property(6, String.class, "OfferID", false, "OFFER_ID");
        public final static Property ProdID = new Property(7, String.class, "ProdID", false, "PROD_ID");
        public final static Property ProSubStatus = new Property(8, String.class, "ProSubStatus", false, "PRO_SUB_STATUS");
        public final static Property SubFunction = new Property(9, String.class, "SubFunction", false, "SUB_FUNCTION");
        public final static Property State = new Property(10, String.class, "State", false, "STATE");
        public final static Property ID = new Property(11, String.class, "ID", false, "ID");
    };


    public EntityWorkLogDgDao(DaoConfig config) {
        super(config);
    }
    
    public EntityWorkLogDgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_WORK_LOG_DG' (" + //
                "'OCCUR_TIME' TEXT," + // 0: OccurTime
                "'USER_ID' TEXT," + // 1: UserID
                "'USER_NAME' TEXT," + // 2: UserName
                "'ORG_CODE' TEXT," + // 3: OrgCode
                "'PARAM_TYPE' TEXT," + // 4: ParamType
                "'PARAM_VALUE' TEXT," + // 5: ParamValue
                "'OFFER_ID' TEXT," + // 6: OfferID
                "'PROD_ID' TEXT," + // 7: ProdID
                "'PRO_SUB_STATUS' TEXT," + // 8: ProSubStatus
                "'SUB_FUNCTION' TEXT," + // 9: SubFunction
                "'STATE' TEXT," + // 10: State
                "'ID' TEXT);"); // 11: ID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_WORK_LOG_DG'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityWorkLogDg entity) {
        stmt.clearBindings();
 
        String OccurTime = entity.getOccurTime();
        if (OccurTime != null) {
            stmt.bindString(1, OccurTime);
        }
 
        String UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindString(2, UserID);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(3, UserName);
        }
 
        String OrgCode = entity.getOrgCode();
        if (OrgCode != null) {
            stmt.bindString(4, OrgCode);
        }
 
        String ParamType = entity.getParamType();
        if (ParamType != null) {
            stmt.bindString(5, ParamType);
        }
 
        String ParamValue = entity.getParamValue();
        if (ParamValue != null) {
            stmt.bindString(6, ParamValue);
        }
 
        String OfferID = entity.getOfferID();
        if (OfferID != null) {
            stmt.bindString(7, OfferID);
        }
 
        String ProdID = entity.getProdID();
        if (ProdID != null) {
            stmt.bindString(8, ProdID);
        }
 
        String ProSubStatus = entity.getProSubStatus();
        if (ProSubStatus != null) {
            stmt.bindString(9, ProSubStatus);
        }
 
        String SubFunction = entity.getSubFunction();
        if (SubFunction != null) {
            stmt.bindString(10, SubFunction);
        }
 
        String State = entity.getState();
        if (State != null) {
            stmt.bindString(11, State);
        }
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(12, ID);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityWorkLogDg readEntity(Cursor cursor, int offset) {
        EntityWorkLogDg entity = new EntityWorkLogDg( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // OccurTime
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UserID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // UserName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // OrgCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ParamType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ParamValue
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // OfferID
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ProdID
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ProSubStatus
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // SubFunction
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // State
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // ID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityWorkLogDg entity, int offset) {
        entity.setOccurTime(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOrgCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setParamType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setParamValue(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOfferID(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setProdID(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setProSubStatus(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSubFunction(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setState(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setID(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityWorkLogDg entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityWorkLogDg entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
